/*
 * generated by Xtext 2.20.0
 */
package org.xtext.expression.ide


/**
 * Use this class to register ide components.
 */
class ExpressionIdeModule extends AbstractExpressionIdeModule {
}
