/*
 * generated by Xtext 2.20.0
 */
package org.xtext.expression.ide;

import com.google.inject.Guice;
import com.google.inject.Injector;
import org.eclipse.xtext.util.Modules2;
import org.xtext.expression.ExpressionRuntimeModule;
import org.xtext.expression.ExpressionStandaloneSetup;

/**
 * Initialization support for running Xtext languages as language servers.
 */
public class ExpressionIdeSetup extends ExpressionStandaloneSetup {

	@Override
	public Injector createInjector() {
		return Guice.createInjector(Modules2.mixin(new ExpressionRuntimeModule(), new ExpressionIdeModule()));
	}
	
}
