/*
 * generated by Xtext 2.20.0
 */
package org.xtext.expression;


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
public class ExpressionStandaloneSetup extends ExpressionStandaloneSetupGenerated {

	public static void doSetup() {
		new ExpressionStandaloneSetup().createInjectorAndDoEMFRegistration();
	}
}
