/*
 * generated by Xtext 2.20.0
 */
package org.xtext.expression


/**
 * Initialization support for running Xtext languages without Equinox extension registry.
 */
class ExpressionStandaloneSetup extends ExpressionStandaloneSetupGenerated {

	def static void doSetup() {
		new ExpressionStandaloneSetup().createInjectorAndDoEMFRegistration()
	}
}
