/*
 * generated by Xtext 2.20.0
 */
package org.xtext.expression.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the Eclipse IDE.
 */
public class ExpressionUiModule extends AbstractExpressionUiModule {

	public ExpressionUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
